import { SecretariaMunicipal } from '../models/secretaria-municipal.model';

export const secretariasMunicipales: SecretariaMunicipal[] = [
  {
    id: 'inspeccion-control-urbano',
    nombre: 'Secretaría de Inspección y Control Urbano',
    responsable: 'Marcos Omentari',
    direccion: 'Presidente Perón y Sidoti',
    telefono: '(221) 469-1356',
    horario: 'Lunes a viernes de 8:00 a 16:00',
    email: 'inspeccionycontrolurbano@ensenada.gov.ar',
  },
  {
    id: 'servicios-publicos',
    nombre: 'Secretaría de Servicios Públicos',
    responsable: 'Edgardo Reyes',
    direccion: 'Corralón Municipal · Camino Néstor Kirchner y Rivadavia',
    telefono: '(221) 469-1254',
    horario: 'Lunes a viernes de 7:00 a 16:00',
  },
  {
    id: 'secretaria-privada',
    nombre: 'Secretaría Privada',
    responsable: 'María Celina Ferella',
    direccion: 'La Merced y Presidente Perón · 4° piso, oficinas 401–402',
    telefono: '(0221) 460-1771 / 460-1772',
    horario: 'Lunes a viernes de 8:00 a 16:00',
    email: 'intendente@ensenada.gov.ar',
  },
  {
    id: 'gobierno',
    nombre: 'Secretaría de Gobierno',
    responsable: 'Dra. María Alejandra Sabio',
    direccion: 'La Merced y Presidente Perón N° 503 · 1° piso, oficina 100',
    telefono: '(0221) 469-4883',
    horario: 'Lunes a viernes de 8:00 a 16:00',
    email: 'gobierno@ensenada.gov.ar',
  },
  {
    id: 'hacienda-produccion',
    nombre: 'Secretaría de Hacienda y Producción',
    responsable: 'Rocío Basso',
    direccion: 'Presidente Perón N° 391',
    telefono: '(0221) 460-1428',
    horario: 'Lunes a viernes de 8:00 a 15:00',
    email: 'hacienda@ensenada.gov.ar',
  },
  {
    id: 'desarrollo-social',
    nombre: 'Secretaría de Desarrollo Social',
    responsable: 'Celina Ferella',
    direccion: 'Leandro N. Alem y Brasil',
    telefono: '(221) 469-1265 · WhatsApp 221 554-3049',
    horario: 'Lunes a viernes de 8:00 a 16:00',
    email: 'desarrollosocial@ensenada.gov.ar',
  },
  {
    id: 'seguridad-justicia',
    nombre: 'Secretaría de Seguridad y Justicia',
    responsable: 'Martín Slobodian',
    direccion: 'La ficha oficial no publica una sede general',
    telefono: '(0221) 469-3155',
    horario: 'Lunes a viernes de 8:00 a 16:00',
  },
  {
    id: 'gestion-publica',
    nombre: 'Secretaría de Gestión Pública',
    responsable: 'Agustín Duscovich',
    direccion: 'La Merced y Presidente Perón · 2° piso, oficina 200',
    telefono: '(221) 460-1770 / 221 400-1504',
    horario: 'Lunes a viernes de 8:00 a 16:00',
    email: 'prensamunicipalidadensenada@gmail.com',
  },
  {
    id: 'salud-medio-ambiente',
    nombre: 'Secretaría de Salud y Medio Ambiente',
    responsable: 'Juan Manuel López Ortega',
    direccion: 'San Martín y De La Paz',
    telefono: '(221) 469-0099 / (221) 469-2403',
    horario: 'Lunes a viernes de 8:00 a 16:00',
    email: 'secsaludensenada@hotmail.com',
  },
  {
    id: 'obras-publicas',
    nombre: 'Secretaría de Obras Públicas',
    responsable: 'José Alberto Núñez',
    direccion: 'La Merced y Presidente Perón · 3° piso, oficina 300',
    telefono: '(221) 469-3702',
    horario: 'Lunes a viernes de 8:00 a 16:00',
    email: 'obrasyservicios@ensenada.gov.ar',
  },
];
